version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  order-service:
    build: ./order-service
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - user-service
      - order-service

  grafana:
    image: grafana/grafana
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./anomaly.log:/var/log/anomaly.log
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  jenkins_home:
  grafana-storage:
